ignore-dev-dependencies = true
ignore-build-dependencies = true

accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "CC0-1.0",
    "Unicode-3.0",
    "Zlib",
    "NCSA",
    "BSL-1.0",
    "LicenseRef-Slint-Royalty-free-2.0", # Allowed since "Made with Slint" graphic is included, and this software is not built for embedded systems
]
