[package]
name = "VNeST"
version = "1.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/main.rs"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
getrandom = { version = "0.3.4", features = ["wasm_js"] }

[dependencies]
cosmic-text = "0.19.0"
image = { version = "0.25.6", features = ["ico"] }
slint = { version = "1.17.1"}
unicode-truncate = "2.0.1"
# text-measurer-harfbuzz = {path = "../text-measurer-harfbuzz"}

[build-dependencies]
slint-build = "1.8.0"
