import { Button, VerticalBox } from "std-widgets.slint";

component WhoWhat {
    out property <string> who;
    out property <string> what;

    in property <length> spacing;

    in property <string> verb;

    forward-focus: Who;

    callback next();

    HorizontalLayout {
        spacing: spacing;
        Rectangle {border-width: 2px ;border-color: blue; 
            Who := TextInput {
                color: black; text: who; vertical-alignment: center; horizontal-alignment: center;
                edited => {who=self.text}
                accepted => {What.focus()}
            }
        }
        Rectangle {border-width: 2px; border-color: blue;
            Text {color: black; text: verb;}
            min-width: parent.width/3.0;
        }
        Rectangle {border-width: 2px; border-color: blue;
            What := TextInput {
                color: black; text: what; vertical-alignment: center; horizontal-alignment: center;
                edited => {what=self.text}
                accepted => {next()}
            }
        }
    }
}

component Verb {
    out property <string> verb;
    in property <length> spacing;

    callback next();

    forward-focus: verb_input;

    HorizontalLayout {
        spacing: spacing;
        Rectangle {border-width: 2px ;border-color: blue; 
            Text {color: black; text: "Vem"; vertical-alignment: center; horizontal-alignment: center;}
        }
        Rectangle {border-width: 2px; border-color: blue;
            verb_input := TextInput {
                color: black; text: verb; vertical-alignment: center; horizontal-alignment: center;
                edited => {verb=self.text}
                accepted => {next()}
            }
            max-width: parent.width/3.0;
        }
        Rectangle {border-width: 2px; border-color: blue;
            Text {color: black; text: "Vad"; vertical-alignment: center; horizontal-alignment: center;}
        }
    }
}

component Component inherits Rectangle {
    in property <percent> padding_percent;
    in property <percent> spacing_percent;
    
    out property <string> name;

    forward-focus: verb;

    callback next();

    VerticalLayout {
        spacing: parent.height*spacing_percent;
        padding: parent.height*padding_percent;

        verb := Verb {
            spacing: parent.width*spacing_percent;
            next => {
                wh1.focus()
            }
        }
        wh1 := WhoWhat {
            spacing: parent.width*spacing_percent;
            verb: verb.verb;
            next => {
                wh2.focus()
            }
        }
        wh2 := WhoWhat {
            spacing: parent.width*spacing_percent;
            verb: verb.verb;
            next => {
                wh3.focus()
            }
        }
        wh3 := WhoWhat {
            spacing: parent.width*spacing_percent;
            verb: verb.verb;
            next => {
                next();
            }
        }
    }
}

export component AppWindow inherits Window {
    property <length> padx: self.width*0.05;
    property <length> pady: self.height*0.05;

    in property <image> ico;

    forward-focus: test;
    background: white;

    title: "VNeST-S";
    icon: ico;

    test := Component {
        padding_percent: 15%;
        spacing_percent: 10%;
    }
}