import "assets/fonts/SpaceMono/SpaceMono-Regular.ttf";
import "assets/fonts/SpaceMono/SpaceMono-Bold.ttf";
import "assets/fonts/SpaceMono/SpaceMono-BoldItalic.ttf";
import "assets/fonts/SpaceMono/SpaceMono-Italic.ttf";
import { Button, AboutSlint } from "std-widgets.slint";
import { BasicPhraseStage, ExpandPhraseStage } from "vnest.slint";

export enum State { menu, about, vnest }

component MainMenu inherits Rectangle {
    width: 100%;
    height: 100%;

    in-out property <State> state;

    VerticalLayout {
        alignment: center;
        spacing: 15px;

        padding: 35px;

        Text {
            text: "Verb - Nätverksstärkande Träning (VNeST-S)";
            font-size: 32px;
            font-weight: 800;
            horizontal-alignment: center;
        }

        Text {
            text: "Verb Network Strengthening Treatment - svensk version";
            font-size: 24px;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            padding-top: 50px;
            width: 50%;

            spacing: 150px;

            Button {
                text: "Starta";

                primary: true;

                clicked => {
                    state = State.vnest;
                }
            }

            Button {
                text: "Om";

                clicked => {
                    state = State.about;
                }
            }
        }
    }
}

component AboutPage inherits Rectangle {
    width: 100%;
    height: 100%;

    in-out property <State> state;

    VerticalLayout {
        padding: 10px;
        alignment: space-around;

        Text {
            text: "Om:";
            horizontal-alignment: center;
            font-weight: FontWeight.bold;
        }

        VerticalLayout {
            padding: 0px;
            alignment: center;

            Text {
                text: "Av: Elmer Nolgren Saldert";
                horizontal-alignment: center;
            }

            StyledText {
                horizontal-alignment: center;
                text: @markdown("Källkod: [github.com/elmer-ns/VNeST](https://github.com/elmer-ns/VNeST)");

                link-clicked(link) => {
                    Platform.open-url(link);
                }
            }
        }

        AboutSlint {
            height: 100px;
            width: 100%;
        }
    }

    Button {
        text: "Tillbaka";
        clicked => {
            state = State.menu;
        }

        x: 20px;
        y: parent.height - self.height - 20px;
    }
}

enum VNeSTState { basic_phrase, expand_phrase }

component VNeST inherits Rectangle {
    in-out property <State> app_state;
    property <VNeSTState> state: VNeSTState.basic_phrase;

    property <bool> second-pass: false;

    property <bool> can-next: state == VNeSTState.basic-phrase ? basic_phrase.can-next : expand_phrase.can-next;

    public function reset() {
        state = VNeSTState.basic-phrase;
        second-pass = false;

        basic_phrase.reset();
        expand_phrase.reset();
    }

    public function next() {
        if !can-next {
            return;
        }
        if state == VNeSTState.basic-phrase {
            basic_phrase.next()
        }
        if state == VNeSTState.expand-phrase {
            expand_phrase.next();
        }
    }
    public function back() {
        if state == VNeSTState.basic-phrase {
            basic_phrase.back()
        }
        if state == VNeSTState.expand-phrase {
            expand_phrase.back();
        }
    }

    VerticalLayout {
        Rectangle {
            basic_phrase := BasicPhraseStage {
                visible: false;
                vertical-stretch: 1;

                exit => {
                    app_state = State.menu;
                    self.reset();
                }

                done => {
                    state = VNeSTState.expand-phrase;
                    expand_phrase.next();
                }
            }

            expand_phrase := ExpandPhraseStage {
                second-pass: second-pass;

                subject: basic_phrase.subject;
                verb: basic_phrase.verb;
                object: basic_phrase.object;

                visible: false;
                vertical-stretch: 1;

                done => {
                    if second-pass {
                        reset();
                        back();
                    } else {
                        reset();
                        second-pass = true;
                    }
                }

                exit => {
                    expand_phrase.reset();
                    state = VNeSTState.basic-phrase;
                }
            }
        }

        states [
            basic_phrase when state == VNeSTState.basic-phrase: {
                basic_phrase.visible: true;
            }
            expand_phrase when state == VNeSTState.expand-phrase: {
                expand_phrase.visible: true;
            }
        ]
        HorizontalLayout {
            alignment: space-between;
            padding: 15px;
            Button {
                text: "Tillbaka";
                clicked => {
                    back()
                }
                y: parent.height - self.height - 20px;
            }

            Button {
                text: "Nästa";
                clicked => {
                    next()
                }

                visible: can-next;

                y: parent.height - self.height - 20px;
            }
        }
    }
}

export component AppWindow inherits Window {
    no-frame: false;
    property <State> state: State.menu;

    title: "VNeST-S";

    changed state => {
        self.focus()
    }

    default-font-family: "Space Mono";
    default-font-size: 28px;
    full-screen: false;

    preferred-width: 600px;
    preferred-height: 500px;

    function next() {
        if state == State.vnest {
            vnest.next()
        }
        if state == State.menu {
            state = State.vnest
        }
        if state == State.about {
            state = State.menu
        }
    }

    function back() {
        if state == State.about {
            state = State.menu
        }
        if state == State.vnest {
            vnest.back()
        }
    }

    states [
        menu when state == State.menu: {
            menu.visible: true;
            about.visible: false;
            vnest.visible: false;
        }
        about when state == State.about: {
            menu.visible: false;
            about.visible: true;
            vnest.visible: false;
        }
        vnest when state == State.vnest: {
            menu.visible: false;
            about.visible: false;
            vnest.visible: true;
        }
    ]

    forward-focus: scope;

    scope := FocusScope {
        capture_key_pressed(event) => {
            // DOWN_ARROW -> next()
            if event.text == "" {
                next();
                return accept;
            }

            // RETURN -> next()
            if event.text == "\n" {
                next();
                return accept;
            }

            // UP_ARROW -> back()
            if event.text == "" {
                back();
                return accept;
            }

            //ESCAPE -> back()
            if event.text == "" {
                back();
                return accept;
            }
            return reject;
        }

        menu := MainMenu {
            state <=> state;
        }

        about := AboutPage {
            state <=> state;
        }

        vnest := VNeST {
            app_state <=> state;
        }
    }
}
