import { StyleMetrics } from "std-widgets.slint";

export component TextBox inherits Rectangle {
    in property <string> text;
    in property <length> font-size;
    in property <color> text-color;
    in property <int> font-weight;

    in property <length> margin_left;
    in property <length> margin_right;

    in property <TextOverflow> overflow;
    in property <TextHorizontalAlignment> horizontal_alignment: center;
    in property <TextVerticalAlignment> vertical_alignment: center;

    border-color: self.background.darker(50%);

    text_e := Text {
        text: text;
        font-size: font-size;
        font-weight: font-weight;
        color: text-color;

        width: parent.width - margin_left - margin_right;
        height: parent.height;

        horizontal-alignment: horizontal_alignment;
        vertical-alignment: vertical_alignment;

        overflow: overflow;
    }
}

export component LineInput inherits Rectangle {
    in-out property <string> text;
    in property <length> font-size;
    in property <color> text-color;
    in property <int> font-weight;

    in property <length> margin_left: 0px;
    in property <length> margin_right: 0px;

    in property <TextOverflow> overflow;
    in property <TextHorizontalAlignment> horizontal_alignment: start;
    in property <TextVerticalAlignment> vertical_alignment: center;

    in property <bool> enabled <=> input.enabled;
    in property <bool> read_only <=> input.read-only;

    out property <bool> has-focus: input.has-focus;

    forward-focus: input;

    border-color: self.background.darker(50%);

    callback accepted();

    Rectangle {
        clip: true;

        width: parent.width - margin_left - input.x - margin_right;
        x: margin_left;

        input := TextInput {
            text <=> text;
            font-size: font-size;
            font-weight: font-weight;
            color: text-color;

            horizontal-alignment: horizontal_alignment;
            vertical-alignment: vertical_alignment;

            x: offset;

            property <length> offset;

            cursor-position-changed(position) => {
                offset = min((root.width - margin_left - margin_right - 1rem) - position.x, 0);
            }

            accepted => {
                accepted()
            }
        }
    }
}
