import { StyleMetrics } from "std-widgets.slint";

export component TextBox {
    in property <string> text;
    in property <length> font-size;
    in property <brush> background;
    in property <color> color;
    in property <int> font-weight;
    in property <length> border-radius;
    in property <length> border-width;

    rect := Rectangle {
        background: background;
        border-color: background.darker(50%);
        border-width: border-width;
        border-radius: border-radius;
        min-width: text_e.width + StyleMetrics.layout-padding * 2;
        min-height: text_e.height + StyleMetrics.layout-padding * 2;
        text_e := Text {
            text: text;
            font-size: font-size;
            font-weight: font-weight;
            color: color;
        }
    }
}

export component WordInput {
    in-out property <string> text;
    in property <length> font-size;
    in property <brush> background;
    in property <color> color;
    in property <int> font-weight;
    in property <length> border-radius;
    in property <length> border-width;

    out property <bool> has-focus: input.has-focus;

    rect := Rectangle {
        background: background;
        border-color: background.darker(50%);
        border-width: border-width;
        border-radius: border-radius;

        input := TextInput {
            text <=> text;
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: font-size;
            font-weight: font-weight;
            color: color;
            single-line: true;
        }
    }
}
