import { StyleMetrics } from "std-widgets.slint";
import { TextBox, WordInput } from "text_box.slint";

export component VNeSTMain inherits Rectangle {
    in-out property <int> stage;

    property <string> verb: "";

    VerticalLayout {
        Rectangle {
            vertical-stretch: 1;
        }

        HorizontalLayout {
            alignment: center;

            spacing: 50px;

            TextBox {
                preferred-width: root.width * 0.15;
                preferred-height: root.height * 0.125;

                border-radius: 5px;
                border-width: 2px;

                text: "Vem";
                font-size: 24px;
                font-weight: 600;
                color: black;
                background: lightblue;
            }

            WordInput {
                preferred-width: root.width * 0.15;
                preferred-height: root.height * 0.125;

                border-radius: 5px;
                border-width: 2px;

                text <=> verb;
                font-size: 24px;
                font-weight: 600;
                color: black;
                background: orangered;
            }

            TextBox {
                preferred-width: root.width * 0.15;
                preferred-height: root.height * 0.125;

                border-radius: 5px;
                border-width: 2px;

                text: "Vad";
                font-size: 24px;
                font-weight: 600;
                color: black;
                background: lightgreen;
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }
    }
}
